from .wish_handler import *
from .pokedex_handler import *
from .start_handler import *
from .help import *
from .ss_handler import *
from .lyrics_handler import *
from .quot import *
from .anime import *
from .math import *
from .fun import *
from .id_handler import *
from .git import *
from .sexy import *
from .afk import *
from .broadcast import *
from .imposter import *
from .upscale import *